// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package chirpletportlet.model;

import chirpletportlet.model.Nest;
import chirpletportlet.model.NestDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect NestDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NestDataOnDemand: @Component;
    
    private Random NestDataOnDemand.rnd = new SecureRandom();
    
    private List<Nest> NestDataOnDemand.data;
    
    public Nest NestDataOnDemand.getNewTransientNest(int index) {
        Nest obj = new Nest();
        setContents(obj, index);
        setStillThere(obj, index);
        return obj;
    }
    
    public void NestDataOnDemand.setContents(Nest obj, int index) {
        String contents = "contents_" + index;
        if (contents.length() > 100) {
            contents = contents.substring(0, 100);
        }
        obj.setContents(contents);
    }
    
    public void NestDataOnDemand.setStillThere(Nest obj, int index) {
        Boolean stillThere = Boolean.TRUE;
        obj.setStillThere(stillThere);
    }
    
    public Nest NestDataOnDemand.getSpecificNest(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Nest obj = data.get(index);
        Long id = obj.getId();
        return Nest.findNest(id);
    }
    
    public Nest NestDataOnDemand.getRandomNest() {
        init();
        Nest obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Nest.findNest(id);
    }
    
    public boolean NestDataOnDemand.modifyNest(Nest obj) {
        return false;
    }
    
    public void NestDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Nest.findNestEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Nest' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Nest>();
        for (int i = 0; i < 10; i++) {
            Nest obj = getNewTransientNest(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
