// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package chirpletportlet.model;

import chirpletportlet.model.Nest;
import chirpletportlet.model.NestDataOnDemand;
import chirpletportlet.model.NestIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NestIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NestIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NestIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NestIntegrationTest: @Transactional;
    
    @Autowired
    private NestDataOnDemand NestIntegrationTest.dod;
    
    @Test
    public void NestIntegrationTest.testCountNests() {
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", dod.getRandomNest());
        long count = Nest.countNests();
        Assert.assertTrue("Counter for 'Nest' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NestIntegrationTest.testFindNest() {
        Nest obj = dod.getRandomNest();
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nest' failed to provide an identifier", id);
        obj = Nest.findNest(id);
        Assert.assertNotNull("Find method for 'Nest' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Nest' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NestIntegrationTest.testFindAllNests() {
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", dod.getRandomNest());
        long count = Nest.countNests();
        Assert.assertTrue("Too expensive to perform a find all test for 'Nest', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Nest> result = Nest.findAllNests();
        Assert.assertNotNull("Find all method for 'Nest' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Nest' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NestIntegrationTest.testFindNestEntries() {
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", dod.getRandomNest());
        long count = Nest.countNests();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Nest> result = Nest.findNestEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Nest' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Nest' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NestIntegrationTest.testFlush() {
        Nest obj = dod.getRandomNest();
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nest' failed to provide an identifier", id);
        obj = Nest.findNest(id);
        Assert.assertNotNull("Find method for 'Nest' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNest(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Nest' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NestIntegrationTest.testMergeUpdate() {
        Nest obj = dod.getRandomNest();
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nest' failed to provide an identifier", id);
        obj = Nest.findNest(id);
        boolean modified =  dod.modifyNest(obj);
        Integer currentVersion = obj.getVersion();
        Nest merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Nest' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NestIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", dod.getRandomNest());
        Nest obj = dod.getNewTransientNest(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Nest' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Nest' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Nest' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NestIntegrationTest.testRemove() {
        Nest obj = dod.getRandomNest();
        Assert.assertNotNull("Data on demand for 'Nest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nest' failed to provide an identifier", id);
        obj = Nest.findNest(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Nest' with identifier '" + id + "'", Nest.findNest(id));
    }
    
}
